name: Windows QMake Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.3'
          host: 'windows'
          arch: 'win64_msvc2017_64'
          tools: 'tools_qtcreator,6.0.2-0,qt.tools.qtcreator'

      - name: Build Setup
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.16'

      - name: Build
        run: |
          call ${{ env.Qt5_Dir }}/bin/qmake skydel_plugin.pro -r CONFIG+=release -spec win32-msvc
          call ${{ env.Qt5_Dir }}/../../Tools/QtCreator/bin/jom/jom -f Makefile
        shell: cmd
